apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extcloud-custom-apps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi
  storageClassName: truenas