apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-occ-upgrade
  labels:
    app.kubernetes.io/name: nextcloud-occ-upgrade
spec:
  schedule: "0 03 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nextcloud-occ-upgrade
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - su -s /bin/sh www-data -c "./occ upgrade"
              env:
                - name: PUID
                  value: "{{ .Values.environment.PUID }}"
                - name: PGID
                  value: "{{ .Values.environment.PGID }}"
                - name: TZ
                  value: "{{ .Values.environment.TZ }}"
                - name: MYSQL_DATABASE
                  value: "{{ .Values.environment.MYSQL_DATABASE }}"
                - name: MYSQL_USER
                  value: "{{ .Values.environment.MYSQL_USER }}"
                - name: MYSQL_PASSWORD
                  value: "{{ .Values.environment.MYSQL_PASSWORD }}"
                - name: MYSQL_HOST
                  value: "{{ .Values.environment.MYSQL_HOST }}"
                - name: REDIS_HOST
                  value: "{{ .Values.environment.REDIS_HOST }}"
                - name: PHP_UPLOAD_LIMIT
                  value: "{{ .Values.environment.PHP_UPLOAD_LIMIT }}"
                - name: APACHE_BODY_LIMIT
                  value: "{{ .Values.environment.APACHE_BODY_LIMIT }}"
              volumeMounts:
                - name: html-volume
                  mountPath: /var/www/html
                - name: custom-apps-volume
                  mountPath: /var/www/html/custom_apps
                - name: config-volume
                  mountPath: /var/www/html/config
                - name: data-volume
                  mountPath: /var/www/html/data
              securityContext:
                runAsUser: 0      # root is needed to switch user with su
                runAsGroup: 0
          volumes:
            - name: html-volume
              persistentVolumeClaim:
                claimName: nextcloud-html-pvc
            - name: custom-apps-volume
              persistentVolumeClaim:
                claimName: nextcloud-custom-apps-pvc
            - name: config-volume
              persistentVolumeClaim:
                claimName: nextcloud-config-pvc
            - name: data-volume
              persistentVolumeClaim:
                claimName: nextcloud-data-pvc
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
