{{- if .Values.secrets.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.secrets.adminToken | quote }}
  openid-client-secret: {{ .Values.secrets.openidClientSecret | quote }}
{{- end }}
