apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- with .Values.bazarr.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.bazarr.replicaCount }}
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      {{- with .Values.bazarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bazarr
    spec:
      {{- with .Values.bazarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.bazarr.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.bazarr.securityContext | nindent 12 }}
          image: "{{ .Values.bazarr.image.repository }}:{{ .Values.bazarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bazarr.image.pullPolicy }}
          {{- with .Values.bazarr.bazarr.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.bazarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.bazarr.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.bazarr.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            {{- with .Values.bazarr.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.bazarr.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bazarr.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.bazarr.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.bazarr.persistence.config.existingClaim }}{{ .Values.bazarr.persistence.config.existingClaim }}{{- else }}bazarr-config{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: media
          {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{- else }}{{ template "jellyfin.fullname" . }}-media{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.bazarr.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bazarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 2 }}
      {{- end }}
      {{- with .Values.bazarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}