apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-torrent
  namespace: main
spec:
  entryPoints:
    - torrent
  routes:
    - match: HostSNI(`*`)
      services:
        - name: transmission
          port: 51413
          serversTransport: main-transmission-transport@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransportTCP
metadata:
  name: transmission-transport
  namespace: main
spec:
  dialTimeout: 40s
  dialKeepAlive: 600s
