apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: {{ include "jellyfin.fullname" . }}
        namespace: main
        port: {{ .Values.jellyfin.service.port }}
        passHostHeader: true
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: radarr
        namespace: main
        port: {{ .Values.radarr.service.port }}
        passHostHeader: true
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: sonarr
        namespace: main
        port: {{ .Values.sonarr.service.port }}
        passHostHeader: true
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: transmission
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`transmission.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: transmission
        namespace: main
        port: {{ .Values.transmission.service.port }}
        passHostHeader: true
  tls:
    certResolver: letsencrypt