apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-basic
spec:
  basicAuth:
    secret: authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
data:
  username: YWRtaW4=
  password: dm9sZGVtb3J0