{{- if and .Values.transmission.persistence.config.enabled (not .Values.transmission.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.transmission.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.transmission.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.transmission.persistence.config.size | quote }}
  {{- with .Values.transmission.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.tdarr.persistence.config.enabled (not .Values.tdarr.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.tdarr.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.tdarr.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.tdarr.persistence.config.size | quote }}
  {{- with .Values.tdarr.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.tdarr.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.tdarr.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.tdarr.persistence.config.size | quote }}
  {{- with .Values.tdarr.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.jellyseer.persistence.config.enabled (not .Values.jellyseer.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.jellyseer.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.jellyseer.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jellyseer.persistence.config.size | quote }}
  {{- with .Values.jellyseer.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.radarr.persistence.config.enabled (not .Values.radarr.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.radarr.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.radarr.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.radarr.persistence.config.size | quote }}
  {{- with .Values.radarr.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.bazarr.persistence.config.enabled (not .Values.bazarr.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.bazarr.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.bazarr.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.bazarr.persistence.config.size | quote }}
  {{- with .Values.bazarr.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.sonarr.persistence.config.enabled (not .Values.sonarr.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.sonarr.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.sonarr.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jellyfin.persistence.config.size | quote }}
  {{- with .Values.sonarr.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.jellyfin.persistence.config.enabled (not .Values.jellyfin.persistence.config.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.jellyfin.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.jellyfin.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jellyfin.persistence.config.size | quote }}
  {{- with .Values.jellyfin.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-media
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  {{- with .Values.persistence.media.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-download
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  {{- with .Values.transmission.persistence.download.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.transmission.persistence.download.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.transmission.persistence.download.size | quote }}
  {{- with .Values.transmission.persistence.download.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}