apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.radarr.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.jellyfin.service.type }}
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.sonarr.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sonarr
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.radarr.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: radarr
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.transmission.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.transmission.service.type }}
  ports:
    - port: 9091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: transmission