apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.jellyfin.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.jellyfin.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if (or (eq .Values.jellyfin.service.type "ClusterIP") (empty .Values.jellyfin.service.type)) }}
  type: ClusterIP
  {{- with .Values.jellyfin.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq .Values.jellyfin.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- with .Values.jellyfin.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.jellyfin.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.jellyfin.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  type: {{ .Values.jellyfin.service.type }}
  {{- end }}
  {{- if .Values.jellyfin.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.jellyfin.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.jellyfin.service.ipFamilies }}
  ipFamilies: 
    {{- toYaml .Values.jellyfin.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- with .Values.jellyfin.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.jellyfin.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: {{ .Values.jellyfin.service.portName | default "http" }}
      port: {{ .Values.jellyfin.service.port }}
      protocol: TCP
      targetPort: http
      {{- if (and (eq .Values.jellyfin.service.type "NodePort") (not (empty .Values.jellyfin.service.nodePort))) }}
      nodePort: {{ .Values.jellyfin.service.nodePort }}
      {{- end }}
  selector:
    {{- include "jellyfin..selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.sonarr.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.radarr.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    {{- with .Values.transmission.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.transmission.service.type }}
  ports:
    - port: 9091
      targetPort: http
      protocol: TCP
      name: http

