apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- with .Values.transmission.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.transmission.replicaCount }}
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      {{- with .Values.transmission.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: transmission
    spec:
      hostNetwork: false
      {{- with .Values.transmission.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.transmission.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.transmission.securityContext | nindent 12 }}
          image: "{{ .Values.transmission.image.repository }}:{{ .Values.transmission.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.transmission.image.pullPolicy }}
          {{- with .Values.transmission.transmission.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - name: torrent-tcp
              containerPort: 51413
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.transmission.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.transmission.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.transmission.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: media
            {{- with .Values.transmission.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.transmission.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.transmission.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.transmission.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.transmission.persistence.config.existingClaim }}{{ .Values.transmission.persistence.config.existingClaim }}{{- else }}transmission-config{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: media
          persistentVolumeClaim:
            claimName: transmission-download
        {{- with .Values.transmission.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.transmission.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 2 }}
      {{- end }}
      {{- with .Values.transmission.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.transmission.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.transmission.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}
