---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: insecure-requests
  namespace: main
spec:
  headers:
    contentSecurityPolicy: "upgrade-insecure-requests"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "wedding-app.fullname" . }}
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wedding.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: {{ include "wedding-app.fullname" . }}
        namespace: main
        port: 80
        passHostHeader: true
      middlewares:
      - name: insecure-requests
        namespace: main
  tls:
    certResolver: letsencrypt
