kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volume.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}