apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "recumed-app.fullname" . }}
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`recumed.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: {{ include "recumed-app.fullname" . }}
        namespace: main
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt