replicaCount: 1

image:
  repository: ghcr.io/homarr-labs/homarr
  tag: latest
  pullPolicy: IfNotPresent

domain: drewspace.ro

env:
  timezone: 'Europe/Bucharest'
  encryptionkey: "" #please fill
  AUTH_PROVIDERS: oidc
  AUTH_OIDC_ISSUER: https://keycloak.drewspace.ro/realms/master/.well-known/openid-configuration
  AUTH_OIDC_CLIENT_SECRET: ""
  AUTH_OIDC_CLIENT_ID: homarr
  AUTH_OIDC_CLIENT_NAME: drewspace
  AUTH_OIDC_AUTO_LOGIN: true
  NEXTAUTH_URL: https://drewspace.ro

persistence:
  storageClass: "nfs"
  volumes:
    conf:
      size: "1Gi"
    work:
      size: "1Gi"
