apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tvheadend.fullname" . }}
  labels:
    {{- include "tvheadend.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tvheadend.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tvheadend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "tvheadend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tvheadend.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: htsp
              containerPort: {{ .Values.service.htspPort }}
              protocol: TCP
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: RUN_OPTS
              value: "{{ .Values.env.RUN_OPTS }}"
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: recordings
              mountPath: {{ .Values.persistence.recordings.mountPath }}
            {{- range .Values.devices }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- range .Values.devices }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "{{ .Values.persistence.config.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.persistence.config.size }}
        {{- if .Values.persistence.config.storageClass }}
        storageClassName: {{ .Values.persistence.config.storageClass }}
        {{- end }}
    - metadata:
        name: recordings
      spec:
        accessModes: [ "{{ .Values.persistence.recordings.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.persistence.recordings.size }}
        {{- if .Values.persistence.recordings.storageClass }}
        storageClassName: {{ .Values.persistence.recordings.storageClass }}
        {{- end }}
