apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab-onboarding.fullname" . }}-secrets
  labels:
    {{- include "homelab-onboarding.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: {{ .Values.config.ldap.bindPassword | quote }}
  DB_PASSWORD: {{ .Values.config.db.password | quote }}
  JWT_SECRET: {{ .Values.config.jwt.secret | quote }}
  SMTP_PASS: {{ .Values.config.smtp.pass | quote }}
