apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- with .Values.readarr.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.readarr.replicaCount }}
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      {{- with .Values.readarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: readarr
    spec:
      {{- with .Values.readarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.readarr.podSecurityContext | nindent 8 }}
      containers:
        - name: readarr
          securityContext:
            {{- toYaml .Values.readarr.securityContext | nindent 12 }}
          image: "{{ .Values.readarr.image.repository }}:{{ .Values.readarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.readarr.image.pullPolicy }}
          {{- with .Values.readarr.readarr.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.readarr.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.readarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readarr.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.readarr.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            {{- if .Values.persistence.externalMedia.enabled }}
            - mountPath: {{ .Values.persistence.externalMedia.mountPath | default "/external-media" }}
              name: external-media
              {{- if .Values.persistence.externalMedia.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
            {{- with .Values.readarr.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.readarr.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.readarr.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.readarr.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.readarr.persistence.config.existingClaim }}{{ .Values.readarr.persistence.config.existingClaim }}{{- else }}readarr-config{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: media
          {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{- else }}{{ template "jellyfin.fullname" . }}-media{{- end }}
          {{- else }}
          emptyDir: {}
           {{- end }}
        {{- if .Values.persistence.externalMedia.enabled }}
        - name: external-media
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.externalMedia.existingClaim }}{{ .Values.persistence.externalMedia.existingClaim }}{{- else }}{{ template "jellyfin.fullname" . }}-external-media{{- end }}
        {{- end }}
        {{- with .Values.readarr.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.readarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readarr.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}
