apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "purghel-app.fullname" . }}
  namespace: websites
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`purghel.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: {{ include "purghel-app.fullname" . }}
        namespace: websites
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt