apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "purghel-app.fullname" . }}
  namespace: purghel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`purghel.drewspace.ro`)
      kind: Rule
      services:                       # [8]
      - kind: Service
        name: {{ include "purghel-app.fullname" . }}
        namespace: purghel
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt