apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "adguard" }}
  labels:
    app: adguard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: adguard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          volumeMounts:
            - name: conf
              mountPath: /opt/adguardhome/conf
            - name: work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: conf
        - name: work
          persistentVolumeClaim:
            claimName: work
