apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`adguard.drewspace.ro`)
      middlewares:
        - name: keycloak-auth-admin
          namespace: main
      services:
        - kind: Service
          name: adguard-web
          namespace: main
          passHostHeader: true
          port: 80
    - kind: Rule
      match: Host(`adguard-setup.drewlocal.ro`)
      services:
        - kind: Service
          name: adguard-web
          namespace: main
          passHostHeader: true
          port: 3000
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-adguard-tcp
  namespace: main
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: adguard-tcp
          port: 53
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressroute-adguard-udp
  namespace: main
spec:
  entryPoints:
    - dns-udp
  routes:
      - services:
        - name: adguard-udp
          port: 53
          nativeLB: true