apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf
  labels:
    app: adguard
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.conf.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work
  labels:
    app: adguard
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.work.size }}
