apiVersion: v1
kind: Service
metadata:
  name: adguard-tcp
spec:
  selector:
    app: adguard
  ports:
    - name: tcp-dns
      protocol: TCP
      port: 53
      targetPort: 53
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-udp
spec:
  selector:
    app: adguard
  ports:
    - name: udp-dns
      protocol: UDP
      port: 53
      targetPort: 53
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
  labels:
    app: adguard
spec:
  selector:
    app: adguard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

