apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
type: Opaque
stringData:
  password.txt: |
    {{ .Values.mosquitto.credentials }}