apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
data:
  password.txt: |
    admin:$7$100$feD9t1MHg+j9jFjI$BUDP5+E+/xHGEEoHX4Wd+5pvGIs3n3emQS0DJzQgASsI5cmTTrzhjo1EuSPEhcTJq3dAmBg8VaicSr3BGhA3Fw==
