apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
data:
  password.txt: |
    aragorn:100000$BitgSeEwPqPG/dJqsOVZIw==$T9+MCoeE0VE8DlNthnUu26eBshphoNFF3QH32UUn7QhRi7Y4cPRlClWI51QfG9qQtlJKVw4w882m9Do9RuYyvw==
