---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.z2m.name }}
  name: zigbee2mqtt-data
spec:
  storageClassName: {{ .Values.persistence.z2m.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mosquitto.name }}
  name: mq-pv-claim
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
status: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.ha.volume.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ha.volume.size }}



