---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.z2m.name }}
  name: {{ .Values.z2m.volume.claimName }}
spec:
  storageClassName: {{ .Values.persistence.z2m.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.z2m.volume.size }}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mosquitto.name }}
  name: {{ .Values.mosquitto.volume.claimName }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mosquitto.volume.size }}
status: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.ha.volume.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ha.volume.size }}