apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "homarr" }}
  labels:
    app: homarr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7575
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.env.timezone }}
            - name: SECRET_ENCRYPTION_KEY
              value: {{ .Values.env.encryptionkey }}
            - name: AUTH_PROVIDERS
              value: {{ .Values.env.AUTH_PROVIDERS }}
            - name: AUTH_OIDC_URI
              value: {{ .Values.env.AUTH_OIDC_URI }}
            - name: AUTH_OIDC_CLIENT_SECRET
              value: {{ .Values.env.AUTH_OIDC_CLIENT_SECRET }}
            - name: AUTH_OIDC_CLIENT_ID
              value: {{ .Values.env.AUTH_OIDC_CLIENT_ID }}
            - name: AUTH_OIDC_CLIENT_NAME
              value: {{ .Values.env.AUTH_OIDC_CLIENT_NAME }}
            - name: AUTH_OIDC_AUTO_LOGIN
              value: {{ .Values.env.AUTH_OIDC_AUTO_LOGIN }}
            - name: NEXTAUTH_URL
              value: {{ .Values.env.NEXTAUTH_URL }}
          volumeMounts:
            - name: appdata
              mountPath: /appdata
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
