apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homarr.drewspace.ro`) || Host(`www.drewspace.ro`) || Host(`drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: homarr-web
        namespace: main
        port: 7575
        passHostHeader: true
  tls:
    certResolver: letsencrypt