apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  labels:
    app: homarr
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.conf.size }}