apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "pihole" }}
  labels:
    app: pihole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          volumeMounts:
            - name: etc-pihole
              mountPath: /etc/pihole
            - name: etc-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: pihole-etc-pihole
        - name: etc-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-etc-dnsmasq
