apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: pihole-web
        namespace: main
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-pihole-tcp
  namespace: main
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: pihole-dns
          port: 53
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressroute-pihole-udp
  namespace: main
spec:
  entryPoints:
    - dns-udp
  routes:
      - services:
        - name: pihole-dns
          port: 53
          nativeLB: true