apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.drewspace.ro`)
      kind: Rule
      services:
      - kind: Service
        name: pihole-web
        namespace: main
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt