apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pihole
  labels:
    app: pihole
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.etcPihole.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-dnsmasq
  labels:
    app: pihole
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.etcDnsmasq.size }}
