apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
    - protocol: UDP
      port: 53
      targetPort: 53
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
