apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- with .Values.prowlarr.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.prowlarr.replicaCount }}
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      {{- with .Values.prowlarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: prowlarr
    spec:
      {{- with .Values.prowlarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.prowlarr.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.prowlarr.securityContext | nindent 12 }}
          image: "{{ .Values.prowlarr.image.repository }}:{{ .Values.prowlarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.prowlarr.image.pullPolicy }}
          {{- with .Values.prowlarr.prowlarr.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.prowlarr.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.prowlarr.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.prowlarr.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.prowlarr.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            {{- with .Values.prowlarr.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.prowlarr.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.prowlarr.initContainers }}
      initContainers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.prowlarr.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.prowlarr.persistence.config.existingClaim }}{{ .Values.prowlarr.persistence.config.existingClaim }}{{- else }}prowlarr-config{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: media
          {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{- else }}{{ template "jellyfin.fullname" . }}-media{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.prowlarr.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.prowlarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prowlarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prowlarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prowlarr.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}