apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.{{ .Values.domain }}`)
      kind: Rule
      services:
      - kind: Service
        name: bazarr
        namespace: main
        port: {{ .Values.bazarr.service.port }}
        passHostHeader: true
      middlewares:
      - name: keycloak-auth-admin
        namespace: main
  tls:
    certResolver: letsencrypt