name: Build and Push Docker Image to GitHub Container Registry

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
    paths:
      - "docker/**"
    

  # Allow manual triggers from the GitHub Actions dashboard
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

       # Build and push multi-arch Docker images
      - name: Build and push Docker images for multi-arch
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          
          # Build and push mysql-app for multi-arch
          docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/mariadb/Dockerfile \
            -t ghcr.io/${{ github.repository }}/mysql-homelab:latest --push .

          # Build and push mariadb for multi-arch
          docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/mariadb/Dockerfile \
            -t ghcr.io/${{ github.repository }}/mariadb-homelab:latest --push .


