apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "uptimekuma.fullname" . }}
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`uptimekuma.drewspace.ro`)
      middlewares:
        - name: keycloak-auth-admin
          namespace: main
      services:
        - kind: Service
          name: {{ include "uptimekuma.fullname" . }}
          namespace: main
          passHostHeader: true
          port: {{ .Values.service.port }}
  tls:
    certResolver: letsencrypt