apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
